task_manager/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("manage/", admin.site.urls),
    path("", include("tasks.urls")),
    path("users/", include("users.urls")),
]

tasks/urls.py
from django.urls import path
from rest_framework_nested import routers
from .api.views import TaskViewSet, TaskHistoryViewSet
from . import views

app_name = 'tasks'

router = routers.DefaultRouter()
router.register(r'api/tasks', TaskViewSet, basename='tasks')

history_router = routers.NestedSimpleRouter(router, r'api/tasks', lookup='task')
history_router.register(r'history', TaskHistoryViewSet, basename='history')

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('pending/', views.PendingTaskView.as_view(), name='pending'),
    path('completed/', views.CompletedTaskView.as_view(), name='completed'),
    path('add/', views.AddTaskView.as_view(), name='add'),
    path('edit/<int:pk>/', views.EditTaskView.as_view(), name='edit'),
    path('delete/<int:id>/', views.DeleteTaskView.as_view(), name='delete'),
    path('schedule_reports/', views.TaskReportView.as_view(), name='schedule_reports'),
] + router.urls + history_router.urls

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/tailwind.css' %}" />
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <title>
        {% block title %}{% endblock %}
    </title>
</head>
<body>
    <div class="h-screen flex justify-center w-full">
        <div class="bg-white px-4 py-8 w-screen max-w-xl">
            <div class="pt-6 pb-8 mb-4">
                <div class="mb-6">
                    <div class="text-center text-3xl place-content-center font-bold">
                        {% block heading %}{% endblock %}
                    </div>
                </div>
                <div class="my-4">
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
    </div>
</body>
</html>

templates/_settings.html
<div class="text-center text-rose-500 text-lg">
    <a href="">Report Settings</a>
</div>

templates/_task_menu.html
<ul class="flex">
    <li class="flex-1 mr-2">
        <a
            {% if request.path == '/' %}
            class="text-center block rounded-full bg-rose-100 text-red-500 hover:bg-red-300 hover:text-red-600 py-3 px-4" href="#"
            {% else %}
            class="text-center block border-white rounded-full text-black hover:bg-rose-50 hover:text-red-500 py-3 px-4" href="{% url 'tasks:index' %}"
            {% endif %}
        >
            All
        </a>
    </li>
    <li class="flex-1 mr-2">
      <a
        {% if request.path == '/pending/' %}
        class="text-center block rounded-full bg-rose-100 text-red-500 hover:bg-red-300 hover:text-red-600 py-3 px-4" href="#"
        {% else %}
        class="text-center block border-white rounded-full text-black hover:bg-rose-50 hover:text-red-500 py-3 px-4" href="{% url 'tasks:pending' %}"
        {% endif %}
      >Pending</a>
    </li>
    <li class="flex-1 mr-2">
        <a 
        {% if request.path == '/completed/' %}
        class="text-center block rounded-full bg-rose-100 text-red-500 hover:bg-red-300 hover:text-red-600 py-3 px-4" href="#"
        {% else %}
        class="text-center block border-white rounded-full text-black hover:bg-rose-50 hover:text-red-500 py-3 px-4" href="{% url 'tasks:completed' %}"
        {% endif %}
        >Completed</a>
    </li>
</ul>