task_manager/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("manage/", admin.site.urls),
    path("", include("tasks.urls")),
    path("users/", include("users.urls")),
]

tasks/urls.py
from django.urls import path
from rest_framework_nested import routers
from .api.views import TaskViewSet, TaskHistoryViewSet
from . import views

app_name = 'tasks'

router = routers.DefaultRouter()
router.register(r'api/tasks', TaskViewSet, basename='tasks')

history_router = routers.NestedSimpleRouter(router, r'api/tasks', lookup='task')
history_router.register(r'history', TaskHistoryViewSet, basename='history')

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('pending/', views.PendingTaskView.as_view(), name='pending'),
    path('completed/', views.CompletedTaskView.as_view(), name='completed'),
    path('add/', views.AddTaskView.as_view(), name='add'),
    path('edit/<int:pk>/', views.EditTaskView.as_view(), name='edit'),
    path('delete/<int:id>/', views.DeleteTaskView.as_view(), name='delete'),
    path('schedule_reports/', views.TaskReportView.as_view(), name='schedule_reports'),
] + router.urls + history_router.urls

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import SignUpView
from .forms import UserLoginForm

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html', authentication_form=UserLoginForm), name='login'),
    path('register/', SignUpView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

tasks/models.py
import datetime

from django.db import models, transaction
from django.utils import timezone
from django.contrib.auth.models import User


STATUS_CHOICES = (
    ("PENDING", "Pending"),
    ("IN_PROGRESS", "In Progress"),
    ("COMPLETED", "Completed"),
    ("CANCELLED", "Cancelled"),
)


class TaskHistory(models.Model):
    task = models.ForeignKey('Task', on_delete=models.CASCADE, related_name='history')
    old_status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="PENDING")
    new_status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="PENDING")
    changed_at = models.DateTimeField(auto_now=True)


class Task(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    priority = models.PositiveIntegerField(default=0)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="PENDING")
    created_date = models.DateTimeField(auto_now=True)
    deleted = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.title

    def summary_history(self):
        return TaskHistory.objects.filter(task=self).order_by('-changed_at')

    @transaction.atomic
    def save(self, *args, **kwargs):
        if self.status == "COMPLETED":
            super().save(*args, **kwargs)
            return
        _priority = self.priority
        tasks = Task.objects.filter(
            user=self.user,
            priority__gte=_priority,
            deleted=False
        ).exclude(id=self.id).select_for_update().order_by('priority')
        updating_tasks = []
        for task in tasks:
            if task.priority > _priority:
                break
            _priority = task.priority = task.priority + 1
            updating_tasks.append(task)
        Task.objects.bulk_update(updating_tasks, ['priority'])

        super(Task, self).save(*args, **kwargs)
        
        summary_history = self.summary_history()
        if not summary_history.exists():
            TaskHistory.objects.create(task=self, old_status='', new_status=self.status)
        if summary_history.first().new_status != self.status:
            TaskHistory.objects.create(task=self, old_status=summary_history.first().new_status, new_status=self.status)


class UserTaskReportSetting(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    report_time = models.TimeField(default=timezone.now, null=True, blank=True)
    last_sent_at = models.DateTimeField()

    def save(self, *args, **kwargs):
        if self.last_sent_at is None:
            self.last_sent_at = timezone.now().replace(hour=self.report_time.hour, minute=self.report_time.minute) - datetime.timedelta(days=1)
        obj = super().save(*args, **kwargs)
        return obj

tasks/forms.py
from django import forms
from django.db import transaction

from .models import Task, STATUS_CHOICES

class TaskForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'bg-slate-100 px-4 py-2 outline-none rounded-md w-full border-0'}))
    description = forms.CharField(widget=forms.Textarea(
        attrs={'class': 'bg-slate-100 px-4 py-2 outline-none rounded-md w-full border-0'}))
    priority = forms.IntegerField(widget=forms.NumberInput(
        attrs={'class': 'bg-slate-100 px-4 py-2 outline-none rounded-md w-full border-0'}))
    status = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                'class': 'bg-slate-100 px-4 py-2 outline-none rounded-md w-full border-0'
            },
        ),
        choices=STATUS_CHOICES
    )

    class Meta:
        model = Task
        fields = ['title', 'description', 'priority', 'status', 'user']

    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) < 3:
            raise forms.ValidationError("Title must be at least 3 characters long.")
        return title.capitalize()

    def clean_priority(self):
        priority = self.cleaned_data['priority']
        if priority < 0:
            raise forms.ValidationError("Priority must non-negative.")
        return priority

tasks/api/views.py
from django.db import transaction
from rest_framework import generics, authentication, permissions, status
from rest_framework.viewsets import ModelViewSet, ReadOnlyModelViewSet
from rest_framework.response import Response

from tasks.models import Task, TaskHistory
from .filters import TaskFilter, TaskHistoryFilter
from .serializers import TaskSerializer, TaskHistorySerializer


class TaskViewSet(ModelViewSet):
    serializer_class = TaskSerializer
    filterset_class = TaskFilter

    permission_classes = [permissions.IsAuthenticated]
    authentication_classes = [authentication.BasicAuthentication]

    def get_queryset(self):
        return Task.objects.filter(user=self.request.user, deleted=False)


class TaskHistoryViewSet(ReadOnlyModelViewSet):
    serializer_class = TaskHistorySerializer
    filterset_class = TaskHistoryFilter

    permission_classes = [permissions.IsAuthenticated]
    authentication_classes = [authentication.BasicAuthentication]    

    def get_queryset(self):
        return TaskHistory.objects.filter(task_id=self.kwargs['task_pk'], task__user=self.request.user).order_by('-changed_at')

tasks/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from django.db import transaction

from .models import Task, UserTaskReportSetting
from .forms import TaskForm

User = get_user_model()


class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'tasks/index.html'
    context_object_name = 'all_tasks'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['count_completed'] = Task.objects.filter(status='COMPLETED', user=self.request.user, deleted=False).count()
        return context

    def get_queryset(self):
        return Task.objects.filter(user=self.request.user, deleted=False).order_by('-status', 'priority')


class PendingTaskView(LoginRequiredMixin, generic.ListView):
    template_name = 'tasks/pending_tasks.html'
    context_object_name = 'pending_tasks'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['count_all'] = Task.objects.filter(deleted=False, user=self.request.user).count()
        return context

    def get_queryset(self):
        return Task.objects.filter(user=self.request.user, deleted=False).exclude(status='COMPLETED').order_by('priority')


class CompletedTaskView(LoginRequiredMixin, generic.ListView):
    template_name = 'tasks/completed_tasks.html'
    context_object_name = 'completed_tasks'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['count_all'] = Task.objects.filter(deleted=False, user=self.request.user).count()
        return context

    def get_queryset(self):
        return Task.objects.filter(user=self.request.user, status='COMPLETED', deleted=False).order_by('priority')


class AddTaskView(LoginRequiredMixin, generic.CreateView):
    template_name = 'tasks/create_task.html'
    form_class = TaskForm
    success_url = '/'

    def form_valid(self, form):
        task = form.save(commit=False)
        task.user = self.request.user
        task.save()
        return super().form_valid(form)


class EditTaskView(LoginRequiredMixin, generic.UpdateView):
    template_name = 'tasks/update_task.html'
    form_class = TaskForm
    success_url = '/'

    def form_valid(self, form):
        task = form.save(commit=False)
        task.user = self.request.user
        task.save()
        return super().form_valid(form)

    def get_queryset(self):
        return Task.objects.filter(user=self.request.user, deleted=False)


class DeleteTaskView(LoginRequiredMixin, View):
    def get(self, request, id):
        Task.objects.filter(id=id).update(deleted=True)
        return redirect('/')


class TaskReportView(LoginRequiredMixin, View):
    def get(self, request):
        report_time = UserTaskReportSetting.objects.get(user=request.user).report_time if \
            UserTaskReportSetting.objects.filter(user=request.user).exists() else None
        usr_email = self.request.user.email
        ctx = {'report_time': report_time, 'usr_email': usr_email}
        return render(request, 'tasks/task_report.html', context=ctx)

    def post(self, request):
        report_time = self.request.POST.get('report_time')
        with transaction.atomic():
            report = UserTaskReportSetting.objects.get_or_create(user=request.user)[0]
            report.report_time = report_time
            report.save()
            usr = User.objects.get(id=self.request.user.id)
            usr.email = self.request.POST.get('usr_email')
            usr.save()
        return redirect('/')

templates/tasks/completed_tasks.html
{% extends '_base.html' %}
{% block title %}Completed Tasks{% endblock %}
{% block heading %}
<div class="columns-2 place-content-center">
    <div class="text-left"><h1>Hi {{ request.user.username }}</h1></div>
    <div class="text-right"><a href="{% url 'users:logout' %}" class="text-sm font-normal text-red-500">Log out</a></div>
</div>
{% endblock %}
{% block content %}
  <p class="text-gray-500 my-4">{{ object_list.count }} of {{ count_all }} tasks completed</p>
  {% include '_task_menu.html' %}
  <div class="overflow-y-auto h-80 lg:h-96 my-6">
    {% for task in object_list %}
    <div class="bg-slate-100 flex justify-between items-center p-4 rounded-xl mt-4">
      <div class="flex justify-start items-center gap-2">
        <div>
          <p class="text-gray-700 text-lg font-medium tracking-wider">
            {% if task.completed %}
              <span class="text-red-500 line-through">
                {{ task.title }}
              </span>
            {% else %}
              <span class="">
                {{task.title}} 
                <span class="inline-flex items-center justify-center px-1 py-1 text-xs font-medium leading-none text-white bg-blue-500 rounded">{{ task.priority }}</span>
              </span>
            {% endif %}
          </p>
          <p class="text-slate-500 text-sm">{{ task.created_date|date:"D j M" }}</p>
        </div>
      </div>
      <div class="flex columns-2 space-x-2">
        <button onclick="javascript:window.location.href='{% url 'tasks:edit' task.id %}'" class="w-full bg-teal-400 font-medium px-2 py-1 rounded-md text-white tracking-wide"><i class="fa fa-pen"></i></button>
        <button onclick="javascript:window.location.href='{% url 'tasks:delete' task.id %}'" class="w-full bg-rose-500 font-medium px-2 py-1 rounded-md text-white tracking-wide"><i class="fa fa-trash"></i></button>
      </div>
    </div>
    {% empty %}
    <p class="text-2xl text-gray-600 my-4 text-center">No tasks to show</p>
    
    {% endfor %}
  </div>
  <button onclick="javascript:window.location.href='{% url 'tasks:add' %}'" class="mt-6 w-full bg-red-500 font-medium py-3 rounded-md text-white tracking-wide">Add</button>
  <p class="mt-4 text-center text-red-500 font-medium">
    <a href="{% url 'tasks:schedule_reports' %}">Report Mailing Schedule</a>
  </p>
{% endblock %}

templates/tasks/create_task.html
{% extends '_base.html' %}
{% block title %}Create Todo{% endblock %}
{% block heading %}
<h1 class="text-left">Create Todo</h1>
{% endblock %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <div class="space-y-4">
          {% if form.errors %}
              {% for error in form.non_field_errors %}
                  <p> {{ error }} </p>
              {% endfor %}
          {% endif %}
          <div>
            <label for="title" class="block mb-1 text-gray-800">Title</label>
            {{ form.title }}
            <p class="text-gray-500 my-2 mx-6">{{ form.title.errors }}</p>
          </div>
          <div>
            <label for="description" class="block mb-1 text-gray-800">Description</label>
            {{ form.description }}
            <p class="text-gray-500 my-2 mx-6">{{ form.description.errors }}</p>
          </div>
          <div>
            <label for="priority" class="block mb-1 text-gray-800">Priority</label>
            {{ form.priority }}
            <p class="text-gray-500 my-2 mx-6">{{ form.priority.errors }}</p>
          </div>
          <div>
            <label for="status" class="block mb-1 text-gray-800">Status</label>
            {{ form.status }}
            <p class="text-gray-500 my-2 mx-6">{{ form.status.errors }}</p>
          </div>
      </div>
      <button class="mt-6 w-full bg-red-500 py-3 rounded-md text-white tracking-wide">Add</button>
    </div>
</form>
{% endblock %}

templates/tasks/index.html
{% extends '_base.html' %}
{% block title %}All Tasks{% endblock %}
{% block heading %}
<div class="columns-2 place-content-center">
    <div class="text-left"><h1>Hi {{ request.user.username }}</h1></div>
    <div class="text-right"><a href="{% url 'users:logout' %}" class="text-sm font-normal text-red-500">Log out</a></div>
</div>
{% endblock %}
{% block content %}
  <p class="text-gray-500 my-4">{{ count_completed }} of {{ all_tasks.count }} tasks completed</p>
  {% include '_task_menu.html' %}
  <div class="overflow-y-auto h-80 lg:h-96 my-6">
    {% for task in all_tasks %}
    <div class="bg-slate-100 flex justify-between items-center p-4 rounded-xl mt-4">
      <div class="flex justify-start items-center gap-2">
        <div>
          <p class="text-gray-700 text-lg font-medium tracking-wider">
            {% if task.status == 'COMPLETED' %}
              <span class="text-red-500 line-through">
                {{ task.title }}
              </span>
            {% else %}
              <span class="">
                {{task.title}} 
                <span class="inline-flex items-center justify-center px-1 py-1 text-xs font-medium leading-none text-white bg-blue-500 rounded">{{ task.priority }}</span>
              </span>
            {% endif %}
          </p>
          <p class="text-slate-500 text-sm">{{ task.created_date|date:"D j M" }}</p>
        </div>
      </div>
      <div class="flex columns-2 space-x-2">
        <button onclick="javascript:window.location.href='{% url 'tasks:edit' task.id %}'" class="w-full bg-teal-400 font-medium px-2 py-1 rounded-md text-white tracking-wide"><i class="fa fa-pen"></i></button>
        <button onclick="javascript:window.location.href='{% url 'tasks:delete' task.id %}'" class="w-full bg-rose-500 font-medium px-2 py-1 rounded-md text-white tracking-wide"><i class="fa fa-trash"></i></button>
      </div>
    </div>
    {% empty %}
    <p class="text-2xl text-gray-600 my-4 text-center">No tasks to show</p>
    
    {% endfor %}
  </div>
  <button onclick="javascript:window.location.href='{% url 'tasks:add' %}'" class="mt-6 w-full bg-red-500 font-medium py-3 rounded-md text-white tracking-wide">Add</button>
  <p class="mt-4 text-center text-red-500 font-medium">
    <a href="{% url 'tasks:schedule_reports' %}">Report Mailing Schedule</a>
  </p>
{% endblock %}

templates/tasks/pending_tasks.html
{% extends '_base.html' %}
{% block title %}Pending Tasks{% endblock %}
{% block heading %}
<div class="columns-2 place-content-center">
    <div class="text-left"><h1>Hi {{ request.user.username }}</h1></div>
    <div class="text-right"><a href="{% url 'users:logout' %}" class="text-sm font-normal text-red-500">Log out</a></div>
</div>
{% endblock %}
{% block content %}
  <p class="text-gray-500 my-4">{{ object_list.count }}  of {{ count_all }} tasks pending</p>
  {% include '_task_menu.html' %}
  <div class="overflow-y-auto h-80 lg:h-96 my-6">
    {% for task in object_list %}
    <div class="bg-slate-100 flex justify-between items-center p-4 rounded-xl mt-4">
      <div class="flex justify-start items-center gap-2">
        <div>
          <p class="text-gray-700 text-lg font-medium tracking-wider">
            {% if task.completed %}
              <span class="text-red-500 line-through">
                {{ task.title }}
              </span>
            {% else %}
              <span class="">
                {{task.title}} 
                <span class="inline-flex items-center justify-center px-1 py-1 text-xs font-medium leading-none text-white bg-blue-500 rounded">{{ task.priority }}</span>
              </span>
            {% endif %}
          </p>
          <p class="text-slate-500 text-sm">{{ task.created_date|date:"D j M" }}</p>
        </div>
      </div>
      <div class="flex columns-2 space-x-2">
        <button onclick="javascript:window.location.href='{% url 'tasks:edit' task.id %}'" class="w-full bg-teal-400 font-medium px-2 py-1 rounded-md text-white tracking-wide"><i class="fa fa-pen"></i></button>
        <button onclick="javascript:window.location.href='{% url 'tasks:delete' task.id %}'" class="w-full bg-rose-500 font-medium px-2 py-1 rounded-md text-white tracking-wide"><i class="fa fa-trash"></i></button>
      </div>
    </div>
    {% empty %}
    <p class="text-2xl text-gray-600 my-4 text-center">No tasks to show</p>
    
    {% endfor %}
  </div>
  <button onclick="javascript:window.location.href='{% url 'tasks:add' %}'" class="mt-6 w-full bg-red-500 font-medium py-3 rounded-md text-white tracking-wide">Add</button>
  <p class="mt-4 text-center text-red-500 font-medium">
    <a href="{% url 'tasks:schedule_reports' %}">Report Mailing Schedule</a>
  </p>
{% endblock %}

templates/tasks/task_report.html
{% extends '_base.html' %}
{% block heading %}
  <h1 class="text-left">Email Report Settings</h1>
{% endblock %}
{% block content %}
<form action="" method="post">
  {% csrf_token %}
  <div class="space-y-4">
    <div>
      <label for="usr_email" class="block mb-1 text-gray-800">Email</label>
      <input type="email" class="bg-slate-100 px-4 py-2 outline-none rounded-md w-full border-0" name="usr_email" id="usr_email" value="{{ usr_email }}" required>
    </div>
    <div>
      <label for="report_time" class="block mb-1 text-gray-800">Email Report Time (UTC)</label>
      <input type="time" class="bg-slate-100 px-4 py-2 outline-none rounded-md w-full border-0" name="report_time" id="report_time" value="{{ report_time|date:'H:i' }}" required>
    </div>
    <button class="mt-6 w-full bg-red-500 py-3 rounded-md text-white tracking-wide">Schedule Email Reports</button>
  </div>
</form>
{% endblock %}

templates/tasks/update_task.html
{% extends '_base.html' %}
{% block title %}Update Todo{% endblock %}
{% block heading %}
<h1 class="text-left">Update Todo</h1>
{% endblock %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <div class="space-y-4">
          {% if form.errors %}
              {% for error in form.non_field_errors %}
                  <p> {{ error }} </p>
              {% endfor %}
          {% endif %}
          <div>
            <label for="title" class="block mb-1 text-gray-800">Title</label>
            {{ form.title }}
            <p class="text-gray-500 my-2 mx-6">{{ form.title.errors }}</p>
          </div>
          <div>
            <label for="description" class="block mb-1 text-gray-800">Description</label>
            {{ form.description }}
            <p class="text-gray-500 my-2 mx-6">{{ form.description.errors }}</p>
          </div>
          <div>
            <label for="priority" class="block mb-1 text-gray-800">Priority</label>
            {{ form.priority }}
            <p class="text-gray-500 my-2 mx-6">{{ form.priority.errors }}</p>
          </div>
          <div>
            <label for="status" class="block mb-1 text-gray-800">Status</label>
            {{ form.status }}
            <p class="text-gray-500 my-2 mx-6">{{ form.status.errors }}</p>
          </div>
      </div>
      <button class="mt-6 w-full bg-red-500 py-3 rounded-md text-white tracking-wide">Add</button>
    </div>
</form>
{% endblock %}